/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIConsole: typeof import('./components/AIConsole.vue')['default']
    OpenclawPage: typeof import('./components/OpenclawPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPage: typeof import('./components/SettingsPage.vue')['default']
    SkillsPage: typeof import('./components/SkillsPage.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
  }
}
