/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentAddWizard: typeof import('./components/AgentAddWizard.vue')['default']
    AgentEditorPage: typeof import('./views/AgentEditorPage.vue')['default']
    AgentsPage: typeof import('./views/AgentsPage.vue')['default']
    AIConsole: typeof import('./components/AIConsole.vue')['default']
    FlowEditorPage: typeof import('./views/FlowEditorPage.vue')['default']
    OnboardOverlay: typeof import('./components/OnboardOverlay.vue')['default']
    OnboardWizardOverlay: typeof import('./components/OnboardWizardOverlay.vue')['default']
    OpenclawPage: typeof import('./views/OpenclawPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPage: typeof import('./views/SettingsPage.vue')['default']
    SetupPage: typeof import('./views/SetupPage.vue')['default']
    SkillsPage: typeof import('./views/SkillsPage.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
  }
}
